stages:
  - linter
  - test
  - build

default:
  image: node:14.19.3-alpine
  tags:
    - docker
  before_script:
    - apk add python3
    - apk add git
    - npm install

linter:
  stage: linter
  script:
    - npm run lint
    - npx eslint test/*

test:
  stage: test
  script:
    - npx ganache-cli -p 9545 > /dev/null &
    - npm test

build:
  stage: build
  script:
    - npm run build
