stages:
  - linter
  - test
  - build

default:
  image: node:14.19.3
  tags:
    - docker
  before_script:
    - apt-get install -y git python3
    - npm install

linter:
  stage: linter
  script:
    - npm run lint
    - npx eslint test/*

test:
  stage: test
  script:
    - npm test

build:
  stage: build
  script:
    - npm run build
