stages:
  - linter
  - test
  - build

linter:
  image: node:14.19.3-alpine
  tags:
    - docker
  stage: linter
  script:
    - npm install
    - npm run lint
    - npx eslint test/*

test:
  image: node:14.19.3-alpine
  tags:
    - docker
  stage: test
  script:
    - npm install
    - npx ganache-cli -p 9545 > /dev/null &
    - npm test

build:
  image: node:14.19.3-alpine
  tags:
    - docker
  stage: build
  script:
    - npm install
    - npm run build
